version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    volumes:
      - sqlite_data:/instance  # Persist SQLite database in the instance folder
    environment:
      FLASK_ENV: development  # Change to production when needed
      SECRET_KEY: "some-random-text"  # Add any required environment variables

volumes:
  sqlite_data:
