name: House Price Estimation App

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python 3.12
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     pytest
    
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:

      - name: Build Docker image
        run: |
          docker build -t house-price-estimation-app ./app

      # - name: Push Docker image to Docker Hub
      #   run: |
      #     echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      #     docker tag house-price-estimation-app ${{ secrets.DOCKER_HUB_USERNAME }}/house-price-estimation-app
      #     docker push ${{ secrets.DOCKER_HUB_USERNAME }}/house-price-estimation-app

      # - name: Deploy to Heroku
      #   run: |
      #     curl https://cli-assets.heroku.com/install.sh | sh
      #     heroku login -i
      #     heroku container:login
      #     heroku container:push web -a house-price-estimation-app
      #     heroku container:release web -a house-price-estimation-app